In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv("mail_data.csv")

In [5]:
df.shape

(5572, 2)

In [9]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:
data = df.where((pd.notnull(df)),'')

In [11]:
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [14]:
data.shape

(5572, 2)

In [15]:
data.loc[data['Category'] == 'spam','Category',]=0
data.loc[data['Category'] == 'ham','Category',]=1

In [19]:
x = data['Message']
y = data['Category']

In [20]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [21]:
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.2,random_state = 3)

In [24]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(5572,)
(4457,)
(1115,)

In [25]:
print(y.shape)
print(y_train.shape)
print(y_test.shape)

(5572,)
(4457,)
(1115,)

In [29]:
feature_extraction = TfidfVectorizer(min_df = 1,stop_words = 'english',lowercase = True)
x_train_features = feature_extraction.fit_transform(x_train)
x_test_features = feature_extraction.transform(x_test)

y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [30]:
model = LogisticRegression()

In [31]:
model.fit(x_train_features,y_train)

LogisticRegression()

In [36]:
prediction = model.predict(x_train_features)
accuracy_train = accuracy_score(y_train,prediction)

In [37]:
print(f"accuracy on training data is {accuracy_train}")

accuracy on training data is 0.9676912721561588

In [39]:
prediction = model.predict(x_test_features)
accuracy_test = accuracy_score(y_test,prediction)

In [40]:
print(f"accuracy on training data is {accuracy_test}")

accuracy on training data is 0.9668161434977578

In [50]:
input_mail = [""]
input_data_features = feature_extraction.transform(input_mail)
prediction = model.predict(input_data_features)

print(prediction)

if(prediction[0] ==1 ):
    print("HAM Mail")
else:
    print("SPAM Mail")

[1]
HAM Mail